<a href="https://colab.research.google.com/github/Swathi-krishnan434/Python_Materials/blob/main/python_programs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
# 1) Develop a python program to read n digit integer number, and separate the
# integer number and display each digit. [Hint: input:5678 output: 5 6 7 8, use:
# floor and mod operators)
# Code:
n = int(input("Enter a number: "))

divisor = 1

while n // divisor >= 10:
    divisor = divisor * 10

while divisor > 0:
    digit = n // divisor
    print(digit, end=" ")
    n = n % divisor
    divisor = divisor // 10

Enter a number: 12345
1 2 3 4 5 

In [5]:
# 2) Develop a python program to accept 4 numbers and display them in sorted
# order using a minimum number of if else stateme

a = int(input("Enter first number: "))
b = int(input("Enter second number: "))
c = int(input("Enter third number: "))
d = int(input("Enter fourth number: "))

numbers = [a, b, c, d]

numbers.sort()

print("Sorted order:", numbers)

Enter first number: 12345
Enter second number: 23456
Enter third number: 123
Enter fourth number: 456
Sorted order: [123, 456, 12345, 23456]


In [ ]:
#another method
a = int(input("Enter first number: "))
b = int(input("Enter second number: "))
c = int(input("Enter third number: "))
d = int(input("Enter fourth number: "))

if a > b:
    a, b = b, a

if c > d:
    c, d = d, c

if a > c:
    a, c = c, a

if b > d:
    b, d = d, b

if b > c:
    b, c = c, b

print("Sorted order:", a, b, c, d)

In [6]:
import statistics

n = int(input("Enter number of elements: "))

numbers = []

for i in range(n):
    num = int(input("Enter number: "))
    numbers.append(num)

mean = statistics.mean(numbers)
median = statistics.median(numbers)
mode = statistics.mode(numbers)
variance = statistics.variance(numbers)
standard_deviation = statistics.stdev(numbers)

print("Mean =", mean)
print("Median =", median)
print("Mode =", mode)
print("Variance =", variance)
print("Standard Deviation =", standard_deviation)

Enter number of elements: 2
Enter number: 123
Enter number: 456
Mean = 289.5
Median = 289.5
Mode = 123
Variance = 55444.5
Standard Deviation = 235.46655813512032


In [7]:
n = int(input("Enter a number: "))

original = n
reverse = 0

while n > 0:
    digit = n % 10
    reverse = reverse * 10 + digit
    n = n // 10

if original == reverse:
    print("Number is Palindrome")
else:
    print("Number is not Palindrome")

Enter a number: 121
Number is Palindrome


In [8]:
n = int(input("Enter an integer: "))

for i in range(1, 11):
    print(n, "x", i, "=", n * i)

Enter an integer: 12
12 x 1 = 12
12 x 2 = 24
12 x 3 = 36
12 x 4 = 48
12 x 5 = 60
12 x 6 = 72
12 x 7 = 84
12 x 8 = 96
12 x 9 = 108
12 x 10 = 120


In [9]:
#reveres using function
numbers = [1, 4, 5, -10]

position = int(input("Enter position: "))

numbers.reverse()

print("Result:", numbers)

Enter position: 45623
Result: [-10, 5, 4, 1]


In [ ]:
#reverse the number
n = int(input("Enter a number: "))

reverse = 0

while n > 0:
    digit = n % 10
    reverse = reverse * 10 + digit
    n = n // 10

print("Reversed number:", reverse)

In [10]:
n = input("Enter an integer number: ")

digit1 = input("Enter first digit to interchange: ")
digit2 = input("Enter second digit to interchange: ")

result = ""

for digit in n:
    if digit == digit1:
        result = result + digit2
    elif digit == digit2:
        result = result + digit1
    else:
        result = result + digit

print("Number after interchange:", result)

Enter an integer number: 456
Enter first digit to interchange: 4
Enter second digit to interchange: 6
Number after interchange: 654


In [11]:
words = ["hello", "good", "how", "simple"]

capitalized_words = []

for word in words:
    capitalized_words.append(word.capitalize())

print("Capitalized list:", capitalized_words)

Capitalized list: ['Hello', 'Good', 'How', 'Simple']


In [13]:
sentence = input("Enter a sentence: ")

words = sentence.split()
word_count = {}

for word in words:
    if word in word_count:
        word_count[word] = word_count[word] + 1
    else:
        word_count[word] = 1

duplicate_count = 0

for word in word_count:
    if word_count[word] > 1:
        duplicate_count = duplicate_count + 1

print("Number of duplicate words:", duplicate_count)

Enter a sentence: helooo heloo am am swathi am
Number of duplicate words: 1


In [14]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

print("Array:")
print(arr)

print("Row Sum:", np.sum(arr, axis=1))
print("Row Mean:", np.mean(arr, axis=1))
print("Row Standard Deviation:", np.std(arr, axis=1))

print("Column Sum:", np.sum(arr, axis=0))
print("Column Mean:", np.mean(arr, axis=0))
print("Column Standard Deviation:", np.std(arr, axis=0))

Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Row Sum: [ 6 15 24]
Row Mean: [2. 5. 8.]
Row Standard Deviation: [0.81649658 0.81649658 0.81649658]
Column Sum: [12 15 18]
Column Mean: [4. 5. 6.]
Column Standard Deviation: [2.44948974 2.44948974 2.44948974]


In [16]:
string = input("Enter a string: ")

count = 0

for ch in string:
    if ch in "aeiouAEIOU":
        count += 1

print("Number of vowels:", count)

Enter a string: i love cat and cat loes me.
Number of vowels: 9


In [17]:
string = input("Enter a string: ")

reverse = string[::-1]

print("Reversed string:", reverse)

Enter a string: madam
Reversed string: madam


In [18]:
numbers = [10, 25, 5, 40, 15]

largest = numbers[0]

for num in numbers:
    if num > largest:
        largest = num

print("Largest element:", largest)

Largest element: 40
